Fix docx compilation error
transifex/openformats pull request #282
Opened 2022-08-17 10:57 UTC by petrosklg

Related to [TX-14233](https://transifex.atlassian.net/browse/TX-14233)

Problem and/or solution
-----------------------

DOCX file fails to be exported due to compilation errors caused by empty tx tags

There was an error raised when parent element does not exist.
This is fixed by adding a check to return if the parent is None. 

How to test
-----------

1. Create a new resource with the .docx file from the ticket.
2. Upload .xliff translation.
3. Click to download translated file.
4. It should not raise any errors.

Reviewer checklist
------------------

Code:
* [ ] Change is covered by unit-tests
* [ ] Code is well documented, well styled and is following [best practices](https://tem.transifex.com)
* [ ] Performance issues have been taken under consideration
* [ ] Errors and other edge-cases are handled properly

PR:
* [ ] Problem and/or solution are well-explained
* [ ] Commits have been squashed so that each one has a clear purpose
* [ ] Commits have a proper commit message [according to TEM](https://tem.transifex.com/github-guide.html#working-on-a-feature)

2022-08-29 11:57 UTC, asgouros-tx commented on openformats/formats/docx.py
> +            return
This is all out "of my league" here. Why don't we respond with e.g. `text_element.decompose()` instead? 
Should we ask for assistance from someone that is more familiar with openformats?

2022-08-29 11:59 UTC, asgouros-tx reviewed
I did run the test-cases locally and indeed the fix seems to work.
However I am not very confident since it's the first time I see openformats.
I would propose that we seek a second reviewer from someone that is more apt to check the correctness of the fix here.

2022-08-29 12:52 UTC, asgouros-tx commented on openformats/tests/formats/docx/test_docx.py
> +        content = self.handler.compile(template, stringset)
Is this case relevant to the issue here?

2022-08-29 14:38 UTC, asgouros-tx commented on openformats/formats/docx.py
> +            return
I tested compilation of the exact same file with the following method:
```
    @classmethod
    def remove_text_element(cls, text_element):
        if text_element.find_parent('w:r') is not None:
            run_parent = text_element.find_parent('w:r').parent
            if run_parent.name == 'hyperlink':
                return text_element.find_parent('w:hyperlink').decompose()

        return text_element.decompose()
```
and produced the same results. 
I am feeling more confident with this approach cause it still uses `text_element.decompose()`

2022-08-30 07:12 UTC, asgouros-tx commented on openformats/tests/formats/docx/test_docx.py
> +        content = self.handler.compile(template, stringset)
I've gave it a check again. Test won't go into new condition imposed from https://github.com/transifex/openformats/pull/282/files#diff-475113b153a36064fc0fff2bdd9944c21a29e17e326364e12cdb9222bdfbda94R228. Please refactor so the change is covered.

2022-08-30 11:06 UTC, petrosklg commented on openformats/formats/docx.py
> +            return
Updated PR with proposed change.

2022-08-31 06:22 UTC, asgouros-tx commented on openformats/tests/formats/docx/test_docx.py
> +        content = self.handler.compile(template, stringset)
Can you check this comment too?

2022-08-31 06:22 UTC, asgouros-tx requested changes
Please also check comment about introduced test.

2022-09-08 15:33 UTC, petrosklg commented on openformats/tests/formats/docx/test_docx.py
> +        content = self.handler.compile(template, stringset)
@asgouros-tx Tests updated.

2022-09-09 06:23 UTC, asgouros-tx approved these changes
:+1:

2022-09-09 14:02 UTC, merged