Reimplement PO parsing to handle msgstrs with spaces
transifex/openformats pull request #294
Opened 2023-01-25 08:25 UTC by kbairak

Problem and/or solution
-----------------------

How to test
-----------

Reviewer checklist
------------------

Code:
* [ ] Change is covered by unit-tests
* [ ] Code is well documented, well styled and is following [best practices](https://tem.transifex.com)
* [ ] Performance issues have been taken under consideration
* [ ] Errors and other edge-cases are handled properly

PR:
* [ ] Problem and/or solution are well-explained
* [ ] Commits have been squashed so that each one has a clear purpose
* [ ] Commits have a proper commit message [according to TEM](https://tem.transifex.com/github-guide.html#working-on-a-feature)

2023-02-07 13:59 UTC, fathineos requested changes

2023-02-07 13:59 UTC, fathineos commented on openformats/formats/po.py
> +                    for occurence in entry.occurrences
super minor: typo double `rr` needed

2023-02-07 13:59 UTC, fathineos commented on openformats/formats/po.py
> +            [":".join([item for item in occurence]) for occurence in occurrences]
super minor: typo double `rr` needed

2023-02-07 13:59 UTC, fathineos commented on openformats/formats/po.py
> +                # - If all entries are empty, then this is a POT file and we shouldn't
useful comment

2023-02-07 13:59 UTC, fathineos commented on openformats/formats/po.py
> +                # - If all entries are empty, then this is a POT file and we shouldn't
I think that it would be helpful to add a var declaring if the file is considered to be `po` or `pot`.

2023-02-07 13:59 UTC, fathineos commented on openformats/formats/po.py
> +                order=next(order),
I think that the order will defer from prior implementation. The `fuzzy` entries were skipped.

2023-02-07 14:09 UTC, fathineos commented on openformats/formats/po.py
> +                if any((value.strip() for value in entry.msgstr_plural.values())):
This was `entry.msgstr_plural` on the previous implementation. I think that it was correct, should we allow spaces if provided in a non pluralized string?

2023-02-07 14:11 UTC, fathineos commented on openformats/formats/po.py
> +                            1: string_data["msgid_plural"],
not relevant to this pull request: Why we explicitely set the `0` and `1` for this pluralized string?

2023-02-08 07:48 UTC, kbairak commented on openformats/formats/po.py
> +                            1: string_data["msgid_plural"],
Because PO files don't follow the indexes we use. When an entry in a PO file has msgstr_plural, the indexes are 0 and 1, not 1 and 5. This means that if we want to use the correct indexes in openformats, we would have to provide the language's plural rules as an argument to `parse` and `compile`, which we decided not to do. So, we pretend that the rules are 0 and 1 (0, 1 and 2 if there are 3 plurals etc) and fix them during postprocessing.

2023-02-08 07:49 UTC, kbairak commented on openformats/formats/po.py
> +                order=next(order),
Will look into it.

2023-02-08 08:10 UTC, kbairak commented on openformats/formats/po.py
> +                order=next(order),
Good catch, it would have slipped my radar. Thanks!

2023-02-09 11:21 UTC, fathineos commented
Please add some pull request description & rebase/squash and we are good to go!

2023-02-15 13:35 UTC, fathineos approved these changes
LGTM

2023-02-15 13:35 UTC, merged