Adding support for WebVTT (Web Video Text Tracks) (.vtt) format
transifex/openformats pull request #337
Opened 2024-05-17 18:18 UTC by dsavinov-actionengine

Problem and/or solution
-----------------------
Adding parsing and compiling for WebVTT (Web Video Text Tracks) (.vtt) format

How to test
-----------
### 1. Running unit-tests
`/openformats/tests/formats/vtt/test_vtt.py` contains tests for vtt
Use `pytest openformats/tests/formats/vtt/test_vtt.py` to run tests

### 2. Through testbed
Use "VTT" handler in the testbed

Reviewer checklist
------------------

Code:
* [ ] Change is covered by unit-tests
* [ ] Code is well documented, well styled and is following [best practices](https://tem.transifex.com)
* [ ] Performance issues have been taken under consideration
* [ ] Errors and other edge-cases are handled properly

PR:
* [ ] Problem and/or solution are well-explained
* [ ] Commits have been squashed so that each one has a clear purpose
* [ ] Commits have a proper commit message [according to TEM](https://tem.transifex.com/github-guide.html#working-on-a-feature)

2024-05-17 18:24 UTC, dsavinov-actionengine commented
@kbairak please review

2024-05-23 06:41 UTC, kbairak reviewed
Overall it looks good. I will take a more thorough look and invoke it through a debugger. I have a feeling some things can be simplified but I will have to experiment a bit. For the time being, just the one comment.

2024-05-23 06:41 UTC, kbairak commented on openformats/formats/vtt.py
> +                            occurrences=f"{start},{end}")
It's good practice to include an `order` with each OpenString. This is somewhat easy to do:

```python
from itertools import count

order = count()
for ... in ...:
    string = OpenString(..., order=next(order))
```

This will ensure each string will get an auto-incrementing value for `order`.

2024-05-30 06:47 UTC, kbairak requested changes
Great work! I think that only the first comment _requires_ a change (the one with the multiple occurrences of `-->`). The rest are optional.

2024-05-30 06:47 UTC, kbairak commented on openformats/formats/vtt.py
> +                timings_index = i
Minor because it is not going to affect performance by a lot, but we could `break` here.

Actually, we _should_ break because the `-->` part could be in an actual subtitle and we want to consider the first occurrence as the timing.

2024-05-30 06:47 UTC, kbairak commented on openformats/formats/vtt.py
> +    def _format_timing(self, timing):
This is part of the standard library. It might be more well-suited. https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

2024-05-30 06:47 UTC, kbairak commented on openformats/formats/vtt.py
> +        string = next(stringset)
There is a small probability (and if we're honest, transifex will probably stop the compilation process before the interpreter gets here) that this will raise a `StopIteration`. Maybe a try/except that raises a `ParseError("stringset cannot be empty")` would fit here.

2024-05-30 06:47 UTC, kbairak commented on openformats/formats/vtt.py
> +                hash_position = end_of_timings + 1
How about:

```suggestion
            try:
                arrow_pos = subtitle_section.index('-->')
            except ValueError:
                hash_position = -1
            else:
                end_of_timings = subtitle_section.index('\n', arrow_pos + len('-->'))
                hash_position = end_of_timings + 1
```

I know mine is longer and this is a styling preference so feel free to ignore but I feel it is more _pythonic_.

2024-05-30 06:47 UTC, kbairak commented on openformats/formats/vtt.py
> +                end_of_timings = subtitle_section.index('\n', arrow_pos + len('-->'))
Could this line raise a `ValueError`?

2024-06-03 11:40 UTC, dsavinov-actionengine commented on openformats/formats/vtt.py
> +                timings_index = i
Done

2024-06-03 11:41 UTC, dsavinov-actionengine commented on openformats/formats/vtt.py
> +    def _format_timing(self, timing):
This function is written based on a similar function in SRT handler. It takes a string as input and returns a string too. The built-in strftime()/strptime() are less convenient here. Let's leave this function as it is?

2024-06-03 11:42 UTC, dsavinov-actionengine commented on openformats/formats/vtt.py
> +        string = next(stringset)
Done

2024-06-03 11:44 UTC, dsavinov-actionengine commented on openformats/formats/vtt.py
> +                hash_position = end_of_timings + 1
In current PR code, `.index('-->')` cannot produce an exception because it is under condition `(.count('-->') > 0)` in the previous line. 
But `.index('\n', arrow_pos + len('-->'))`  (in both current code and in your suggestion) can give an exception.
So in the new commit there is a rework.

2024-06-10 13:51 UTC, kbairak approved these changes
Great work!

2024-06-11 06:17 UTC, merged