Adding support for ARB (Application Resource Bundle) (.arb) format
transifex/openformats pull request #338
Opened 2024-05-24 14:45 UTC by dsavinov-actionengine

Problem and/or solution
-----------------------
Adding parsing and compiling for ARB (Application Resource Bundle) (.arb) format

How to test
-----------
### 1. Running unit-tests
`/openformats/tests/formats/arb/test_arb.py` contains tests for arb
Use `pytest /openformats/tests/formats/arb/test_arb.py` to run tests

### 2. Through testbed
Use "ARB" handler in the testbed

Reviewer checklist
------------------

Code:
* [ ] Change is covered by unit-tests
* [ ] Code is well documented, well styled and is following [best practices](https://tem.transifex.com)
* [ ] Performance issues have been taken under consideration
* [ ] Errors and other edge-cases are handled properly

PR:
* [ ] Problem and/or solution are well-explained
* [ ] Commits have been squashed so that each one has a clear purpose
* [ ] Commits have a proper commit message [according to TEM](https://tem.transifex.com/github-guide.html#working-on-a-feature)

2024-05-24 14:46 UTC, dsavinov-actionengine commented
Tagging @kbairak for review, but feel free to tag others if needed

2024-06-12 06:59 UTC, kbairak requested changes
Great job!

2024-06-12 06:59 UTC, kbairak commented on openformats/formats/json.py
> +                    self._find_keys(value, key)
Instead of going infinitely deep, we could instead search up to level two and collect entries that are non-text. This way we don't have to bother with escaping keys etc. Here is an idea; I haven't tested it so there might be a few errors:

```python
class ArbHandler(JsonHandler):
    ...

    def parse(self, content, **kwargs):
        ...

        keys = self._find_keys(parsed)
        stringset = self._extract(parsed, keys)

    def _find_keys(self, parsed):
        if parsed.type != dict:
            raise ParseError("...")

        keys, keys_to_ignore = set(), set()
        for key, key_position, value, _ in parsed:
            if not key.startswith("@"):
                if not isinstance(value, str):
                    continue
                if key in keys:
                    raise ParseError(
                        f"Duplicate string key ('{key}') in line "
                        f"{self.transcriber.line_number}"
                    )
                keys.add(key)
            else:
                if isinstance(value, DumbJson):
                    (inner_value, _), = value.find_children('type')
                    if inner_value == "text":
                        keys_to_ignore.add(key)
        return keys - keys_to_ignore

    def _extract(self, parsed, keys):
        stringset = []
        for key, _, value, value_position in parsed:
            if key not in keys:
                continue
            ...
        return stringset
```

2024-06-12 06:59 UTC, kbairak commented on openformats/formats/json.py
> +    def compile(self, template, stringset, **kwargs):
So, the only reason you re-define `compile` and `_copy_until_and_remove_section` is so that you can add the `keep_sections` functionality, which is only needed for testing. I am not very fond of this idea. It makes the code unnecessarily complex. However, there is a case where not removing the sections makes sense.

This is not adequately described in the docs, but when Transifex invokes this handler, it will pass `is_source` as a keyword argument. In this case, we can be certain that

1. the stringset will not be missing anything and that
2. the user wants to get the exact same file they previously uploaded

So, if this is indeed the same use-case, maybe you can rename `keep_sections` to `is_source`.

In any case, lets make sure that when `is_source=True` is passed to `compile`, the end result is the same as the originally uploaded file.

2024-06-12 06:59 UTC, kbairak commented on openformats/formats/json.py
> +        if parsed.type == dict:
No need for this check, we already did it in `_find_keys`. Perhaps to make it clearer, lets make one check in `parse` and then in `_find_keys` and `_extract` assume that `parsed` represents a dict.

2024-06-12 10:01 UTC, kbairak commented
There is another issue I am concerned about. Looking at the examples of the [official Flutter documentation](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#setting-up), it looks like the language files are supposed to be more bare: only key-translation pairs without any metadata.

![image](https://github.com/transifex/openformats/assets/1336464/872e0056-e3b9-4e9d-bf03-7c8a9ded76a8)

So, the question is: should we follow this? should we make sure that when `is_source=False` during `compile`, only the key-translation pairs should be present while when `is_source=True` we should make sure that they get back the same file they originally uploaded?

Have you looked into this?

2024-06-21 14:09 UTC, dsavinov-actionengine commented on openformats/formats/json.py
> +                    self._find_keys(value, key)
Did not try this. Anyway, ARBs normally have only two levels of json, so we don't expect infinite nesting.

2024-06-21 14:10 UTC, dsavinov-actionengine commented on openformats/formats/json.py
> +    def compile(self, template, stringset, **kwargs):
Tried this, replaced `keep_sections` with `is_source`, but that did not work, unit-tests failed. Anyway, re-definition of the `compile()` method is necessary now, as it handles language code for ARB.

2024-06-21 14:11 UTC, dsavinov-actionengine commented on openformats/formats/json.py
> +        if parsed.type == dict:
done

2024-06-21 14:14 UTC, dsavinov-actionengine commented
> There is another issue I am concerned about. Looking at the examples of the [official Flutter documentation](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#setting-up)

...
>should we make sure that when is_source=False during compile, only the key-translation pairs should be present while when is_source=True we should make sure that they get back the same file they originally uploaded?
> Have you looked into this?

Did not implement this logic in the latest commit. It looks unusual if compared to other openformats handlers, which have their compiled files as similar as possible to the source files (only strings from stringset change). Maybe we could try to get back to this idea in a separate pull-request.

2024-06-21 14:15 UTC, dsavinov-actionengine commented on openformats/formats/json.py
> +                context_value = self.metadata[context_key] \
Implemented issue 1 from QA spreadsheet

2024-06-21 14:16 UTC, dsavinov-actionengine commented on openformats/formats/json.py
> +        if language_info is not None:
Implemented issue 2 from QA spreadsheet

2024-06-21 14:16 UTC, dsavinov-actionengine commented on openformats/formats/json.py
> +                description_value = self.metadata[description_key] \
Implemented issue 3 from QA spreadsheet

2024-06-25 13:26 UTC, kbairak approved these changes

2024-06-25 13:33 UTC, merged